### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by markroxor** [jellAIfish/jellyfish#51]
- [ ] Generate code using RNN
- [ ]  Generate images using RNN
- [ ] Read Andrej's blog http://karpathy.github.io/neuralnets/
- [ ]  GAN - https://deeplearning4j.org/generative-adversarial-network
- [ ] Read Denny Britz blog - http://blog.dennybritz.com/

**Comment by markroxor** [comment]
* GAN - https://deeplearning4j.org/generative-adversarial-network

**Comment by markroxor** [comment]
- [ ] Post all your BMI research from local notebooks to github.

**Comment by markroxor** [comment]
- [ ] combine LSTM learning to code with reinforcement learning, where reward would depend on the number of compiler errors and warnings for the resulting code.

**Comment by markroxor** [comment]
Not the right place!
